name: ToLivre
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  go_router: ^14.7.2
  auto_route: ^9.3.0+1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.2.0
  flutter_local_notifications: ^18.0.1
  intl: ^0.20.2
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/logo.png